site_name: Gradle Community Site
site_author: Gradle Contributors
site_description: >-
  This is an open-source site for all Gradle community matters,
  including governance, artwork, events, and public infrastructure.
copyright: >
  Copyright &copy; 2024 - All contributors to the repository and included components.
  The original content licenses and copyrights from the included repositories are preserved,
  you can find them in the linked repositories.

  Gradle and the Gradlephant logo (the "Gradle Marks") are registered trademarks of Gradle, Inc. and/or its subsidiaries.
  Use of the Gradle Marks the Gradle Cookbook pages is for identification purposes only and does not imply sponsorship or endorsement by Gradle, Inc.
  In the Gradle Cookbook, "Gradle" typically means "Gradle Build Tool" and does not reference Gradle Inc. and/or its subsidiaries.
docs_dir: docs
repo_url: https://github.com/gradle/community
repo_name: Gradle Community repo
edit_uri: edit/main/docs/
site_url: https://community.gradle.org

# Build
site_dir: _site

# Theme
theme:
  name: material
  custom_dir: overrides/
  highlightjs: true
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    # NOT compatible qith toc.integrate
    # - navigation.indexes
    - navigation.path
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    # TODO: use the site's scheme
    # text: Lato Lite
    code: Roboto Mono
  favicon: images/logos/gradle.svg
  logo: images/logos/gradle.svg
  icon:
    repo: fontawesome/brands/github


extra_css:
  - assets/css/gradle.css
extra_javascript:
  - assets/js/google-tag-support.js

extra:
  social:
    - icon: fontawesome/brands/slack
      link: https://gradle.org/slack-invite
      name: Slack
    - icon: fontawesome/brands/github
      link: https://github.com/gradle
      name: GitHub
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/gradle
      name: Twitter/X
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/gradle
      name: LinkedIn
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@Gradle
      name: Mastodon
  analytics:
    provider: custom

nav:
  - Home: README.md
  - Cookbook: https://cookbook.gradle.org/
  - Hacktoberfest 2024: events/hacktoberfest/2024/README.md
  - Participate:
    - Getting Started: contributing/README.md
    - Community Slack: contributing/community-slack.md
    - Spread the Word: contributing/spread-the-word.md
    - Contributing to Gradle Build Tool:
      - Overview: gradle/CONTRIBUTING.md
      - Gradle Build Tool Architecture: gradle/architecture/README.md
    - Contributing to Documentation:
      - Overview: contributing/documentation/README.md
      - Gradle Build Tool Docs: gradle/platforms/documentation/docs/README.md
      - Community Site Docs: CONTRIBUTING.md
      - Gradle Cookbook: cookbook/docs/CONTRIBUTING.md
    - Reporting Vulnerabilities: dotgithub/SECURITY.md
    - Public Roadmap: roadmap/README.md
    - Code of Conduct: dotgithub/CODE_OF_CONDUCT.md
  - Events:
      - Events Overview: events/README.md
      - 2024 Developer Survey: surveys/developer-survey/README.md
      - Hacktoberfest: events/hacktoberfest/README.md
      - Google Summer of Code:
        - Overview: events/gsoc/README.md
        - Gradle Build Server - Support for Android projects: events/gsoc/2024/gradle-build-server-android.md
        - Gradle Build Server - DevX and Language Support in Buildship: events/gsoc/2024/gradle-build-server-devx.md
        - Declarative Syntax and Enhancements for the Checkstyle Plugin: events/gsoc/2024/checkstyle-plugin.md
  - Resources:
    - Key Resources: resources/README.md
    - Public Roadmap: roadmap/README.md
    - Code of Conduct: dotgithub/CODE_OF_CONDUCT.md
    - Social Media: resources/social-media.md
    - Trademark and Branding: https://gradle.com/brand/
    - Books: resources/books.md

plugins:
  - search
  - autorefs
# FIXME: Collision on GitHub Actions, to be fixed later
#  - macros
  - mkdocs-pdf
  # OpenGraphs
  - social:
      cards_layout_options:
        background_color: "#010002"
        font_family: Lato
  - group:
      enabled: !ENV [FULL_BUILD, true]
      plugins:
      - multirepo:
          cleanup: false
          keep_docs_dir: true
          nav_repos:
          - name: dotgithub
            import_url: 'https://github.com/gradle/.github?branch=master&edit_uri=/blob/master/'
          - name: gradle
            import_url: 'https://github.com/gradle/gradle?branch=master&edit_uri=/blob/master/'
            imports: [ "/*.md", "/*.png", "platforms/documentation/docs/README.md", "architecture/*", "architecture/standards/*" ]
          - name: roadmap
            import_url: 'https://github.com/gradle/build-tool-roadmap?branch=main&edit_uri=/blob/main/'
            imports: [ "README.md" ]
          - name: gradle-profiler
            import_url: 'https://github.com/gradle/gradle-profiler?branch=master&edit_uri=/blob/master/'
            imports: [ "README.md" ]
          - name: declarative-gradle
            import_url: 'https://github.com/gradle/declarative-gradle?branch=main&edit_uri=/blob/main/'
            imports: [ "README.md", "**/README.md" ]
          - name: github-actions
            import_url: 'https://github.com/gradle/actions?branch=main&edit_uri=/blob/main/'
            imports: [ "README.md", "*" ]
          - name: cookbook
            import_url: 'https://github.com/gradle/cookbook?branch=main&edit_uri=/blob/main/'
            imports: [ "docs/CONTRIBUTING.md" ]

  - redirects:
      redirect_maps:
        'events/hacktoberfest/README.md' : 'events/hacktoberfest/2024/README.md'
        'cookbook/README.md' : https://cookbook.gradle.org/

# Markdown
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: '#'
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - mdx_truly_sane_lists
